# Generated by Django 3.0.5 on 2020-06-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_screening'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.Film')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.Screening')),
            ],
        ),
    ]
