# Generated by Django 3.0.5 on 2020-06-14 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_filmscreening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='filmscreening',
            name='start_hour',
        ),
        migrations.AlterField(
            model_name='filmscreening',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para esta sesión particular', primary_key=True, serialize=False),
        ),
    ]
