# Generated by Django 3.0.5 on 2020-06-14 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Descripción del cine', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta sala de cine', primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Descripción de la sala', max_length=500)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema')),
            ],
        ),
    ]
