# Generated by Django 3.0.5 on 2020-06-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200614_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='description',
            field=models.TextField(help_text='Descripción de la sala', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(help_text='Descripción del cine', max_length=500, null=True),
        ),
    ]
