# Generated by Django 3.0.5 on 2020-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20200614_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='local_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
