# Generated by Django 3.0.5 on 2020-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20200614_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
