# Generated by Django 3.0.5 on 2020-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='seat_number',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
