# Generated by Django 3.0.5 on 2020-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0008_auto_20200615_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FilmScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta sesión particular', primary_key=True, serialize=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billboard.Film')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.Screening')),
            ],
        ),
    ]
